### PR TITLE
Merged branch

### PR DESCRIPTION
**Pull request by xintamosaik**
This is the merge after I tried to rebase the navbar branch.

### CODE REVIEW

**Comment by xintamosaik** [comment]
Can you please do a thorough review if this is not destroying past improvements?

**Comment by xintamosaik** [comment]
And sorry I made a mess

**Review by steph-koopmanschap — APPROVED** [review]
Tested the branch and everything seems to work correctly.

**Comment by xintamosaik** [comment]
I'm relly relieved to hear it -.-

**Review by med4kat — APPROVED** [review]

**Pull request merged**
